[workspace.package]
version = "0.1.0"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[workspace]
resolver = "2"
members = [
    # Binaries
    "src/binaries",
    # Common
    "src/common/arrow",
    "src/common/auth",
    "src/common/base",
    "src/common/building",
    "src/common/cache",
    "src/common/compress",
    "src/common/exception",
    "src/common/grpc",
    "src/common/hashtable",
    "src/common/http",
    "src/common/io",
    "src/common/metrics",
    "src/common/openai",
    "src/common/tracing",
    "src/common/storage",
    "src/common/vector",
    "src/common/license",
    # Query
    "src/query/ast",
    "src/query/codegen",
    "src/query/config",
    "src/query/constraint",
    "src/query/catalog",
    "src/query/sharing",
    "src/query/sharing-endpoint",
    "src/query/datavalues",
    "src/query/expression",
    "src/query/formats",
    "src/query/functions",
    "src/query/management",
    "src/query/pipeline/core",
    "src/query/pipeline/sinks",
    "src/query/pipeline/sources",
    "src/query/pipeline/transforms",
    "src/query/profile",
    "src/query/settings",
    "src/query/sql",
    "src/query/storages/common/blocks",
    "src/query/storages/common/cache",
    "src/query/storages/common/cache-manager",
    "src/query/storages/common/index",
    "src/query/storages/common/parquet",
    "src/query/storages/common/pruner",
    "src/query/storages/common/table-meta",
    "src/query/storages/factory",
    "src/query/storages/fuse",
    "src/query/storages/hive/hive",
    "src/query/storages/hive/hive-meta-store",
    "src/query/storages/iceberg",
    "src/query/storages/information-schema",
    "src/query/storages/memory",
    "src/query/storages/null",
    "src/query/storages/random",
    "src/query/storages/share",
    "src/query/storages/stage",
    "src/query/storages/system",
    "src/query/storages/view",
    "src/query/storages/parquet",
    "src/query/storages/parquet_v2",
    "src/query/storages/result_cache",
    "src/query/users",
    "src/query/ee-features/vacuum-handler",
    "src/query/ee-features/background-service",
    "src/query/ee-features/aggregating-index",
    "src/query/ee-features/data-mask",
    "src/query/ee-features/table-lock",
    # databend-query
    "src/query/service",
    # enterprise
    "src/query/ee",
    # Meta
    "src/meta/api",
    "src/meta/app",
    "src/meta/embedded",
    "src/meta/kvapi",
    "src/meta/process",
    "src/meta/raft-store",
    "src/meta/sled-store",
    "src/meta/stoerr",
    "src/meta/store",
    "src/meta/types",
    "src/meta/ee",
    # meta proto
    "src/meta/proto-conv",
    "src/meta/protos",
    # databend-meta
    "src/meta/service",
    # sqllogictest
    "tests/sqllogictests",

    "src/bendpy",
]

[workspace.dependencies]
# databend maintains:
sled = { git = "https://github.com/datafuse-extras/sled", tag = "v0.34.7-datafuse.1", default-features = false }
opendal = { version = "0.37", features = [
    "layers-tracing",
    "layers-metrics",
    "services-ipfs",
    "services-moka",
    "services-redis",
    "trust-dns",
] }
ethnum = { version = "1.3.2" }
ordered-float = { version = "3.6.0", default-features = false }
jsonb = { git = "https://github.com/datafuselabs/jsonb", rev = "fe6835a" }

# openraft = { version = "0.8.2", features = ["compat-07"] }
# For debugging
openraft = { git = "https://github.com/drmingdrmer/openraft", tag = "v0.8.4-alpha.3", features = ["compat-07"] }

# type helper
derive_more = "0.99.17"
lazy_static = "1.4.0"

# error
anyhow = { version = "1.0.65" }
anyerror = { version = "=0.1.8" }
thiserror = { version = "1" }

# versioning
semver = "1.0.14"

# CLI
clap = { version = "3.2.22", features = ["derive", "env"] }

# server
tonic = { version = "0.9.2", features = ["transport", "codegen", "prost", "tls-roots", "tls"] }

# serialization
prost = { version = "0.11.0" }
serde = { version = "1.0.164", features = ["derive", "rc"] }
serde_json = { version = "1.0.85", default-features = false, features = ["preserve_order"] }
tonic-build = { version = "0.9.2" }

# chrono
chrono = { version = "0.4.24", features = ["serde"] }
chrono-tz = "0.6.3"

# memory
bumpalo = "3.12.0"
tikv-jemalloc-ctl = { version = "0.5.0", features = ["use_std"] }

# http
reqwest = { version = "0.11", default-features = false, features = [
    "json",
    "rustls-tls",
    "rustls-tls-native-roots",
    "trust-dns",
] }

# runtime
tokio = { version = "1.26.0", features = ["full"] }

# backtrace
async-backtrace = "0.2.2"

[profile.release]
debug = 1
lto = "thin"
overflow-checks = false
incremental = false
opt-level = "s"
# codegen-units = 1       # Reduce number of codegen units to increase optimizations.

# [profile.release.package]
# arrow2 = { codegen-units = 4 }
# common-functions = { codegen-units = 16 }
# databend-query = { codegen-units = 4 }
# databend-binaries = { codegen-units = 4 }

[profile.bench]
debug = true
overflow-checks = false

[profile.dev]
split-debuginfo = "unpacked"
overflow-checks = false
# wait until https://github.com/rust-lang/rust/issues/100142 fixed
incremental = false

[profile.dev.package]
addr2line = { opt-level = 3 }
adler = { opt-level = 3 }
gimli = { opt-level = 3 }
miniz_oxide = { opt-level = 3 }
object = { opt-level = 3 }
rustc-demangle = { opt-level = 3 }

[profile.test]
opt-level = 0
debug = 0
codegen-units = 16
lto = false
debug-assertions = true
overflow-checks = true
rpath = false

[patch.crates-io]
# If there are dependencies that need patching, they can be listed below.

arrow2 = { git = "https://github.com/jorgecarleitao/arrow2", rev = "031bc7bc" }
arrow-format = { git = "https://github.com/sundy-li/arrow-format", rev = "c8e11341" }
parquet2 = { git = "https://github.com/jorgecarleitao/parquet2", rev = "693c265" }
metrics = { git = "https://github.com/datafuse-extras/metrics.git", rev = "fc2ecd1" }
croaring = { git = "https://github.com/RoaringBitmap/croaring-rs", rev = "13a71b4" }
