[package]
name = "common-storages-parquet-v2"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
doctest = false
test = false

[dependencies]
arrow-schema = "40.0.0"
common-arrow = { path = "../../../common/arrow" }
common-base = { path = "../../../common/base" }
common-catalog = { path = "../../catalog" }
common-exception = { path = "../../../common/exception" }
common-expression = { path = "../../expression" }
common-functions = { path = "../../functions" }
common-meta-app = { path = "../../../meta/app" }
common-pipeline-core = { path = "../../pipeline/core" }
common-pipeline-sources = { path = "../../pipeline/sources" }
common-storage = { path = "../../../common/storage" }
parquet = "40.0.0"

storages-common-index = { path = "../common/index" }
storages-common-pruner = { path = "../common/pruner" }
storages-common-table-meta = { path = "../common/table-meta" }

async-backtrace = { workspace = true }
async-trait = { version = "0.1.57", package = "async-trait-fn" }
chrono = { workspace = true }
futures = "0.3.24"
opendal = { workspace = true }
serde = { workspace = true }
tracing = "0.1.36"
typetag = "0.2.3"

[dev-dependencies]
common-sql = { path = "../../sql" }
