[package]
name = "common-catalog"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
doctest = false
test = false

[dependencies]
common-arrow = { path = "../../common/arrow" }
common-base = { path = "../../common/base" }
common-exception = { path = "../../common/exception" }
common-expression = { path = "../expression" }
common-io = { path = "../../common/io" }
common-meta-app = { path = "../../meta/app" }
common-meta-types = { path = "../../meta/types" }
common-pipeline-core = { path = "../pipeline/core" }
common-profile = { path = "../profile" }
common-settings = { path = "../settings" }
common-storage = { path = "../../common/storage" }

arrow-schema = { version = "40.0.0", features = ["serde"] }
async-backtrace = { workspace = true }
async-trait = "0.1.57"
chrono = { workspace = true }
dashmap = "5.4"
dyn-clone = "1.0.9"
parking_lot = "0.12"
parquet_rs = { package = "parquet", version = "40.0.0" }
rand = "0.8.5"
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = "0.10.6"
typetag = "0.2.3"

[dev-dependencies]
goldenfile = "1.4"
