[package]
name = "common-meta-api"
version = "0.1.0"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common-base = {path = "../../base" }
common-datavalues = {path = "../../datavalues" }
common-exception = {path = "../../exception" }
common-meta-types = {path= "../types" }
common-planners = {path = "../../planners"}
common-tracing = { path = "../../tracing" }



anyhow = "1.0.45"
async-trait = "0.1"
futures = "0.3"
maplit = "1.0.2"
